services:
  nest:
    image: ghcr.io/cesizen/api/nest:main
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]

volumes:
    postgres: